### ISSUE TITLE
Release relative paths fix for HHVM < 4

### ISSUE THREAD

**Issue by traviscrawford** [hhvm/hhvm-autoload#34]
Please tag a new release for HHVM 3.x that includes "use relative paths for require_once statement in generated autoload map" https://github.com/hhvm/hhvm-autoload/commit/4d66f5af76be1de6b4c4f709abe09fb0c7fcb642 (e.g.: either `v1.7.1` or `v1.8`)

**Comment by fredemmott** [comment]
if there's no problems, I'll do 1.8 at 5d3fdbf7c203b05e13edab7b4f9981b19877f368

the shell-out-to-autoload thing makes upgrades in the future a little easier: if you have that, the upgrade 'just works', otherwise you need to delete vendor/ so that php doesn't load the old version of the composer plugin, which uses `HH\string` as a type

**Comment by fredemmott** [comment]
Done
